wikitweet/wikitweet/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from apps.web.views import HomeView, QueryView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^q/(?P<query>[\w-]+)/$', QueryView.as_view(), name='query'),
    url(r'^q/(?P<query>[\w-]+)/(?P<lat>(-?\d+\.\d+))/(?P<lng>(-?\d+\.\d+))/$',
        QueryView.as_view(), name='geo_query'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

wikitweet/apps/web/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)
    geo = forms.BooleanField(required=False)
    latitude = forms.FloatField(required=False)
    longitude = forms.FloatField(required=False)

wikitweet/apps/web/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import HttpResponseRedirect
from django.utils.text import slugify
from django.views.generic import FormView, TemplateView
from libs.wikiTweetSearch import WikiTweetSearch
from .forms import SearchForm


class HomeView(FormView):
    template_name = 'home.html'
    form_class = SearchForm

    def form_valid(self, form):
        query = slugify(form.cleaned_data['query'])
        lat = form.cleaned_data['latitude']
        lng = form.cleaned_data['longitude']

        if lat and lng:
            return HttpResponseRedirect(reverse_lazy('geo_query', kwargs={'query': query, 'lat': lat, 'lng': lng}))
        else:
            return HttpResponseRedirect(reverse_lazy('query', kwargs={'query': query}))


class QueryView(TemplateView):
    template_name = 'query.html'
    api = WikiTweetSearch()

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        query = kwargs.get('query', '')
        lat = kwargs.get('lat', None)
        lng = kwargs.get('lng', None)

        if query:
            context['query'] = query.replace('-', ' ')
            context['twitter'] = self.api.twitter_search(query, lat, lng)
            context['wikipedia'] = self.api.wiki_search(query, lat, lng)

        return self.render_to_response(context)

wikitweet/templates/base.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>WikiTweet</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="{% static 'assets/ico/apple-touch-icon.png' %}">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <style>
        body { padding-top: 50px; padding-bottom: 20px; }
    </style>
</head>
<body>
<!--[if lt IE 8]><p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p><![endif]-->
<div class="container">
    {% block container %} {% endblock %}
</div>
<!-- /container -->
<hr>

<footer>
    <div class="container">
        <p class="text-center"><small>WikiTweet 2015, made with </small>♥</p>
    </div>
</footer>
{% block js %}
<script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js' %}"></script>
{% endblock %}
</body>
</html>

wikitweet/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
    <h1>WikiTweet</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form" method="post">
                        <div class="form-group">
                            <label class="sr-only" for="exampleInputAmount">Search a Topic</label>
                            {% if form.query.errors %}
                                <span class="text-danger"> {{ form.query.errors.as_text }}</span>
                            {% endif %}
                            <div class="input-group {% if form.query.errors %}has-error{% endif %}">
                                {% csrf_token %}
                                <input type="text" class="form-control input-lg" id="id_query" name="query"
                                       placeholder="Topic">

                                <div class="input-group-addon btn">
                                    <button type="submit" id="search" class="btn btn-primary btn-lg btn-submit">Search</button>
                                </div>
                            </div>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input id="id_geo" name="geo" type="checkbox"> Limit result those near me.
                            </label>
                            <input id="id_latitude" name="latitude" type="hidden">
                            <input id="id_longitude" name="longitude" type="hidden">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'assets/js/main.min.js' %}"></script>
{% endblock %}

wikitweet/templates/query.html
{% extends 'base.html' %}

{% block container %}
    <h1>WikiTweet
        <small> results for <strong><i>{{ query }}</i></strong></small>
    </h1>
    <a class="btn btn-xs btn-default" href="{% url 'home' %}">Back and search another topic</a>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">Twitter</div>
                <ul class="list-group">
                    {% for item in twitter %}
                        <li class="list-group-item">
                            <div class="media">
                                <div class="media-left">
                                    <img src="{{ item.image }}" alt="{{ item.user }}"/>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading h5">{{ item.user }}</p>
                                    {{ item.text|safe }}
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">No result found :(</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-warning">
                <!-- Default panel contents -->
                <div class="panel-heading">Wikipedia</div>
                <!-- List group -->
                <ul class="list-group">
                    {% for item in wikipedia %}
                        <li class="list-group-item">
                            <a class="btn btn-link btn-wikipedia" href="{{ item.url }}" target="_blank">{{ item.title }}</a>
                        </li>
                    {% empty %}
                        <li class="list-group-item">No result found :(</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}